version: '2'
services:
  api:
    build: .
    volumes:
      - ./server:/naive-cms/server
    ports:
      - '4000:4000'
    links:
      - mongo

  mongo:
    image: mongo
    logging:
      driver: 'none'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
